# Generated by Django 4.1 on 2022-09-01 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestion',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 14, 19, 8, 683473, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 14, 19, 8, 684852, tzinfo=datetime.timezone.utc)),
        ),
    ]
