# Generated by Django 4.1 on 2022-09-01 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntVoshod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 14, 19, 8, 698762, tzinfo=datetime.timezone.utc)),
        ),
    ]
