# Generated by Django 4.1 on 2022-09-05 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntVoshod', '0002_alter_usermsg_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 19, 33, 22, 45098, tzinfo=datetime.timezone.utc)),
        ),
    ]
